import type { NextPage } from "next";
import Head from "next/head";
import MainBody from "../components/MainBody";

const Home: NextPage = (posts) => {
  console.log(process.env.NEXT_PUBLIC_CONTRACT_ADDRESS);
  return (
    <>
      <Head>
        <title>zkNews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <MainBody />
      </div>
    </>
  );
};

export default Home;

// export async function getServerSideProps() {
//   console.log(process.env.MAIN_PRIVATE_KEY);

//   return {
//     props: {
//       hello: "world",
//     },
//   };
// }

Home.getInitialProps = async () => {
  const res = await fetch("http://localhost:3000/api/posts");
  const { data } = await res.json();

  return { posts: data };
};
